name: Deploy

on: 
  push: 
    branches: [ "master" ]
  pull_request:
    branhces: [ "master" ]

jobs:
  deploy_zip:
    name: deploy to lambda function
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Adjust to your golang version
        go-version: [1.18.4]
    steps:
      - name: checkout source code
        # use latest action on this current version
        uses: actions/checkout@v3

      - name: Install Go
        # use latest action on this current version
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -a -o main main.go && zip main.zip main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Upload Zip
        run: aws lambda update-function-code --function-name {{ YOUR_FUNCTION_NAME }} --zip-file fileb://main.zip
